### Rejstracja
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "kuba@example.com",
  "password": "superbezpiecznehaslo",
  "name": "Kuba"
}

### Logowanie i pobranie tokenu
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "kuba@example.com",
  "password": "superbezpiecznehaslo"
}

> {%
    // Ta funkcja automatycznie zapisze token z odpowiedzi do zmiennej globalnej auth_token
    client.global.set("auth_token", response.body.token);
%}

### Tworzenie nowego Wydarzenia (Event)
POST http://localhost:8080/api/events
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Domowka",
  "location": "Gliwice"
}

### Pobranie listy wydarzeń (Aby sprawdzić ID Twojego wydarzenia)
GET http://localhost:8080/api/events
Authorization: Bearer {{auth_token}}